/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FlushSyncImport } from './routes/flushSync'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FlushSyncRoute = FlushSyncImport.update({
  id: '/flushSync',
  path: '/flushSync',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/flushSync': {
      id: '/flushSync'
      path: '/flushSync'
      fullPath: '/flushSync'
      preLoaderRoute: typeof FlushSyncImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flushSync': typeof FlushSyncRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flushSync': typeof FlushSyncRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/flushSync': typeof FlushSyncRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flushSync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flushSync'
  id: '__root__' | '/' | '/flushSync'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlushSyncRoute: typeof FlushSyncRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlushSyncRoute: FlushSyncRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flushSync"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/flushSync": {
      "filePath": "flushSync.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
